# theme = "kanagawa-clear"
theme = "rose_pine_moon"

[editor]
shell = ["fish", "-c"]
mouse = false
# rulers = [80]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
# Some nice Helix stuff
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

0 = "goto_line_start"
G = "goto_file_end"
"$" = "goto_line_end"

H = ":buffer-previous"
L = ":buffer-next"

D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

C-n = [
  "extend_line",
  ":insert-output echo 'FILL_THIS'",
  "extend_line_below",
  ":pipe sgpt code 'Using this comment, fill the line with the comment FILL_THIS.'"
]

[keys.normal.space]
w = ":write"
c = "toggle_comments"
O = [":new", ":insert-output pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme rose_pine_moon"]
o = ":run-shell-command zellij run -fc -- xplr"
q = ":buffer-close"

[keys.normal.backspace]
g = ":run-shell-command zellij run -fc -- lazygit"
f = ":run-shell-command zellij run -fc -- broot"

[keys.insert]
C-f = "move_char_right"
C-b = "move_char_left"
C-n = [
  "normal_mode",
  "extend_line",
  ":insert-output echo 'FILL_THIS'",
  "extend_line_below",
  ":pipe sgpt code 'Using this comment, fill the line with the comment FILL_THIS.'"
]

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
tab = ["insert_mode", "collapse_selection"] # tab is read by most terminal editors as "C-i"
C-a = ["append_mode", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
