[language-server.lexical]
command = "/Users/box/Code/tools/lexical/_build/dev/package/lexical/bin/start_lexical.sh"

[[language]]
name = "elixir"
file-types = ["ex", "exs", "heex"]
language-servers = ["lexical"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
 
# [[language]]
# name = "heex"
# language-servers = ["lexical"]
# auto-format = true
# indent = { tab-width = 2, unit = "  " }
